### ISSUE TITLE
Duplicate reference names in DB

### ISSUE THREAD

**Issue by AvdReis** [FGPLab/cydrasil#10]
Hi guys

Great work on the DB :)

Just a heads up that I spotted some duplicate reference names in the database, which causes an issue for assignment - no sequences were flagged as duplicate.

sed 's/#.*//' cydrasil-v3-sequence-list.fasta.txt | sort | uniq -cd 

2 >CY-NCBI-EF537059.1
2 >CY-NCBI-KF417640.1

egrep -i ">CY-NCBI-EF537059.1|>CY-NCBI-KF417640.1" cydrasil-v3-sequence-list.fasta.txt

>CY-NCBI-KF417640.1#g__Aphanothece.s__sacrum.str__SAG2412
>CY-NCBI-KF417640.1#g__Anathece.s__clathrata.str__SAG23-99
>CY-NCBI-EF537059.1#g__Hormoscilla.s__spongeliae.str__SI04-42
>CY-NCBI-EF537059.1#g__Hormoscilla.s__spongeliae.str__SI04-46

I personally changed these to:
>CY-NCBI-KF417640.1.1#g__Aphanothece.s__sacrum.str__SAG2412
>CY-NCBI-KF417640.1.2#g__Anathece.s__clathrata.str__SAG23-99
>CY-NCBI-EF537059.1.1#g__Hormoscilla.s__spongeliae.str__SI04-42
>CY-NCBI-EF537059.1.2#g__Hormoscilla.s__spongeliae.str__SI04-46

sed -i 's/>CY-NCBI-KF417640.1#g__Aphanothece.s__sacrum.str__SAG2412/>CY-NCBI-KF417640.1.1#g__Aphanothece.s__sacrum.str__SAG2412/' cydrasil-v3-sequence-list.fasta.txt
sed -i 's/>CY-NCBI-KF417640.1#g__Anathece.s__clathrata.str__SAG23-99/>CY-NCBI-KF417640.1.2#g__Anathece.s__clathrata.str__SAG23-99/' cydrasil-v3-sequence-list.fasta.txt
egrep -i ">CY-NCBI-EF537059.1|>CY-NCBI-KF417640.1" ../../../../Databases/cydrasil-v3-sequence-list.fasta.txt
sed -i 's/>CY-NCBI-EF537059.1#g__Hormoscilla.s__spongeliae.str__SI04-42/>CY-NCBI-EF537059.1.1#g__Hormoscilla.s__spongeliae.str__SI04-42/' cydrasil-v3-sequence-list.fasta.txt
sed -i 's/>CY-NCBI-EF537059.1#g__Hormoscilla.s__spongeliae.str__SI04-46/>CY-NCBI-EF537059.1.2#g__Hormoscilla.s__spongeliae.str__SI04-46/' cydrasil-v3-sequence-list.fasta.txt

I made a fasta and taxonomy file that is Qiime2 compatible, attached.
[cydrasil-v3-sequence-list.tax.txt](https://github.com/FGPLab/cydrasil/files/7151480/cydrasil-v3-sequence-list.tax.txt)
[cydrasil-v3-sequence-list.fasta.txt](https://github.com/FGPLab/cydrasil/files/7151481/cydrasil-v3-sequence-list.fasta.txt)

:)

**Comment by droush** [comment]
Hi @AvdReis !

Thanks for catching this. It looks like it was a typo during the extensive manual re-curation, and didn't get caught during the last bit of checking.

The second sequences in each pair have the wrong NCBI accession number. It should be:
`CY-NCBI-KM020006.1#g__Anathece.s__clathrata.str__SAG23-99`

and 

`CY-NCBI-EF537061.1#g__Hormoscilla.s__spongeliae.str__SI04-46`

I'll do a quick check on the entire database to make sure there were no other issues like this and push out an update here and on the web app this week.

**Comment by droush** [comment]
This will be corrected in an upcoming release.
